# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Test ]
  pull_request:
    branches: [ Test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./flutter_ci
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.15.18'
    - run: ls
      working-directory: ./flutter_ci
    - run: flutter pub get
      working-directory: ./flutter_ci
    - run: flutter test
      working-directory: ./flutter_ci
    - run: flutter build apk
      working-directory: ./flutter_ci
